- name: Run linters
  run: |
    #!/usr/bin/env bash
    set -xeu -o pipefail
    mkdir -p reports/{mypy,isort,pylint}
    mypy . --config-file pyproject.toml
    isort . --check-only | tee -a reports/isort/isort.log
    pylint . --rcfile=pyproject.toml | tee -a reports/pylint/pylint.log
