name: CI build
run-name: CI job triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on: [workflow_dispatch]

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run secrets scanning
        if: runner.os == 'Linux'
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

      - name: Initialize python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run Python linter
        if: runner.os == 'Linux'
        uses: sunnysid3up/python-linter@master
        with:
          source: "."
          mypy-options: "--config-file pyproject.toml"
          pylint-options: "--rcfile=pyproject.toml"
          isort-options: "--check-only"
          django: false

      - name: Run unit tests
        run: python -m unittest ./tests/unittests.py

      - name: Run SCA scan
        if: runner.os == 'Linux'
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt

      - name: Build package
        run: pyinstaller -F pyresizer.py

      - name: Run binary (Linux)
        if: runner.os == 'Linux'
        run:  ./dist/pyresizer -h

      - name: Run binary (Windows)
        if: runner.os == 'Windows'
        run:  ./dist/pyresizer.exe -h
