name: CI build
run-name: CI job triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on: [workflow_dispatch]

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run secrets scanning
        if: runner.os == 'Linux'
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

      - name: Initialize python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run linters
        if: runner.os == 'Linux'
        run: |
          #!/usr/bin/env bash
          set -xeu -o pipefail
          mkdir -p reports/{mypy,isort,pylint}
          mypy . --config-file pyproject.toml
          isort . --check-only | tee -a reports/isort/isort.log
          pylint . --rcfile=pyproject.toml | tee -a reports/pylint/pylint.log

      - name: Run unit tests
        if: runner.os == 'Linux'
        run: coverage run -m unittest tests/unittests.py

      - name: Check code coverage
        if: runner.os == 'Linux'
        run: |
          coverage xml | true
          coverage report -m

      - name: Run SCA scan
        if: runner.os == 'Linux'
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt

      - name: Build package
        run: pyinstaller -F pyresizer.py

      - name: Run binary (Linux)
        if: runner.os == 'Linux'
        run:  ./dist/pyresizer -h

      - name: Run binary (Windows)
        if: runner.os == 'Windows'
        run:  ./dist/pyresizer.exe -h
