name: CI build
run-name: CI job triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on: [workflow_dispatch]

jobs:

  preparation:
    name: Preparation
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install packages
        run: pip install -r requirements.txt

  quality-checks:
    name: Run quality checks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: ./.github/includes/quality-checks.yml

  unit-tests:
    name: Run unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run unit tests
      if: runner.os == 'Linux'
      run: coverage run -m unittest tests/unittests.py

    - name: Check code coverage
      if: runner.os == 'Linux'
      run: |
        coverage xml | true
        coverage report -m

  security-scans:
    name: Run security scans
    runs-on: "ubuntu-latest"
    steps:
    - uses: ./.github/includes/security-scans.yml

  build-package:
    name: Build package
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Build package
      run: pyinstaller -F pyresizer.py

  e2e-tests:
    name: Run e2e tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run binary (Linux)
      if: runner.os == 'Linux'
      run:  ./dist/pyresizer -h

    - name: Run binary (Windows)
      if: runner.os == 'Windows'
      run:  ./dist/pyresizer.exe -h
