name: CI workflow
run-name: CI workflow triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on: [workflow_dispatch]

env:
  PYTHON_VERSION: "3.9"

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: coverage run -m unittest tests/unittests.py

      - name: Check code coverage
        run: |
          coverage xml | true
          coverage report -m

  quality-checks:
    name: Run quality checks
    uses: ./.github/workflows/quality-checks.yml
    with:
      python_version: ${{ env.PYTHON_VERSION }}

  security-scans:
    name: Run security scans
    uses: ./.github/workflows/security-scans.yml

  build-package:
    name: Build package
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - unit-tests
      - quality-checks
      - security-scans
    steps:
      - name: Build package
        run: pyinstaller -F pyresizer.py
    # Add step to create tar.gz and zip packages

  e2e-tests:
    name: Run e2e tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build-package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run binary (Linux)
        if: runner.os == 'Linux'
        run: ./dist/pyresizer -h

      - name: Run binary (Windows)
        if: runner.os == 'Windows'
        run: ./dist/pyresizer.exe -h
