name: Quality checks workflow

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        description: "Provide python version in format x.y"
        required: true

jobs:
  quality-checks:
    name: Run quality checks
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run linters
        run: |
          #!/usr/bin/env bash
          set -xeu -o pipefail
          mkdir -p reports/{mypy,isort,pylint}
          mypy . --config-file pyproject.toml
          isort . --check-only | tee -a reports/isort/isort.log
          pylint . --rcfile=pyproject.toml | tee -a reports/pylint/pylint.log
